ping:
  handler: ${self:custom.path.app}/handlers/ping.handler
  description: Ping test
  reservedConcurrency: 1
  events:
    - http:
        path: ping
        method: get
        private: false
        cors: ${self:custom.http.cors}

pingAuth:
  handler: ${self:custom.path.app}/handlers/ping.handler
  description: Ping test with authentication
  reservedConcurrency: 1
  events:
    - http:
        path: ping/auth
        method: get
        private: true
        cors: ${self:custom.http.cors}

pingQueue:
  handler: ${self:custom.path.app}/handlers/pingQueue.handler
  description: Ping queued test
  memorySize: 192
  reservedConcurrency: 1
  events:
    - http:
        path: ping/queue
        method: get
        private: true
        cors: ${self:custom.http.cors}

pingQueueProcessor:
  handler: ${self:custom.path.app}/handlers/pingQueueProcessor.handler
  description: Process queued ping
  memorySize: 128
  reservedConcurrency: 3
  events:
    - sqs: arn:aws:sqs:${self:provider.region}:${env:AWS_ACCOUNT_ID}:${self:provider.stackName}-pingQueue

pingScheduledEvent:
  handler: ${self:custom.path.app}/handlers/pingScheduledEvent.handler
  description: Ping event triggered from Scheduled Cloudwatch Event
  events:
    - schedule:
        name: ${self:provider.stackName}-pingScheduledEvent
        description: Trigger pingScheduledEvent lambda function every 5 minute
        rate: rate(5 minutes)
        enabled: false
